image: node:6.11.0

cache:
  paths:
  - node_modules/

deploy:
  environment: firebase

  only:
    - master

  before_script:
   - npm install -g firebase-tools
   - npm install
  
  script:
   - npm run build:prod
   - firebase deploy --token $FIREBASE_TOKEN
